name = "graph-ibo-problem-maker"
main = "src/index.ts"
compatibility_date = "2024-07-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "bio-db-prod"
database_id = "c9996dd7-4ae7-4b30-882f-e905517288fc"

# R2 Bucket Binding
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "bio-images"

# AI Binding
[ai]
binding = "AI"

[vars]
# GEMINI_API_KEY = ""
# OPENAI_API_KEY = ""
# DEEPSEEK_API_KEY = ""
# DOUBAO_API_KEY = ""
# TONGYI_API_KEY = ""
# SERPAPI_KEY = ""

# [browser]
# binding = "MYBROWSER"
